version: '3.4'

services:
  libv4l-build:
    container_name: libv4l-build
    build:
      context: .
      dockerfile: dockerfiles/docker-libv4l-build/Dockerfile
      args:
        - RUST_VER=${RUST_VER}
    command: |
      bash -xc "
      rustup override set ${RUST_VER}
      cargo build
      cargo build --examples
      "

  libv4l-build-cross-armhf:
    container_name: libv4l-build-cross-armhf
    build:
      context: .
      dockerfile: dockerfiles/docker-libv4l-build-cross-armhf/Dockerfile
      args:
        - RUST_VER=${RUST_VER}
    command: |
      bash -xc "
      rustup override set ${RUST_VER}
      cargo build --target=arm-unknown-linux-gnueabihf
      cargo build --target=arm-unknown-linux-gnueabihf --examples
      "
