version: '3.4'

services:
  cross-build-rpi:
    container_name: cross-build-rpi
    build:
      context: .
      args:
        - RUST_VER=${RUST_VER}
        - TARGET_ARCH=${TARGET_ARCH}
    command: |
      bash -xc "
      rustup override set ${RUST_VER}
      cargo build --target=${TARGET_ARCH}
      cargo build --target=${TARGET_ARCH} --examples
      "
