version: '3.4'

services:
  libv4l-build:
    container_name: libv4l-build
    build:
      context: .
      dockerfile: dockerfiles/docker-libv4l-build/Dockerfile
      args:
        - RUST_CHANNEL=${RUST_CHANNEL}
    command: |
      bash -xc "
      rustup override set ${RUST_CHANNEL}
      cargo build
      cargo build --examples
      "

  libv4l-test:
    container_name: libv4l-build
    build:
      context: .
      dockerfile: dockerfiles/docker-libv4l-build/Dockerfile
      args:
        - RUST_CHANNEL=${RUST_CHANNEL}
    command: |
      bash -xc "
      rustup override set ${RUST_CHANNEL}
      cargo test --all
      "

  libv4l-build-cross-armhf:
    container_name: libv4l-build-cross-armhf
    build:
      context: .
      dockerfile: dockerfiles/docker-libv4l-build-cross-armhf/Dockerfile
      args:
        - RUST_CHANNEL=${RUST_CHANNEL}
    command: |
      bash -xc "
      rustup override set ${RUST_CHANNEL}
      cargo build --target=arm-unknown-linux-gnueabihf || cargo build --target=arm-unknown-linux-gnueabihf  # FIXME: build fails in 1st build... https://app.circleci.com/pipelines/github/Idein/libv4l-sys/102/workflows/2e538f9c-c15a-4798-bc58-c9a7ac0c5faf/jobs/334
      cargo build --target=arm-unknown-linux-gnueabihf --examples
      "
