version: 2.1

executors:
  default:
    docker:
      - image: docker/compose
    working_directory: /tmp/libv4l_sys

constants:
  parameter-rust-version: &parameter-rust-version
    rust:
      type: string
      default: "1.36.0"

commands:
  setup_docker_compose:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Install git
          command: apk add --update --no-cache git
      - run: git merge --no-edit origin/master

jobs:
  build:
    parameters:
      <<: *parameter-rust-version
    executor: default
    steps:
      - setup_docker_compose
      - run:
          name: Build w/ rustc ver. << parameters.rust >>
          environment:
            RUST_CHANNEL: << parameters.rust >>
          command: |
            docker-compose build libv4l-build
            docker-compose run --rm libv4l-build

  test:
    parameters:
      <<: *parameter-rust-version
    executor: default
    steps:
      - setup_docker_compose
      - run:
          name: Test w/ rustc ver. << parameters.rust >>
          environment:
            RUST_CHANNEL: << parameters.rust >>
          command: |
            docker-compose build libv4l-test
            docker-compose run --rm libv4l-test

  cross_build:
    parameters:
      <<: *parameter-rust-version
    executor: default
    steps:
      - setup_docker_compose
      - run:
          name: Cross build w/ rustc ver. << parameters.rust >>
          environment:
            RUST_CHANNEL: << parameters.rust >>
          command: |
            docker-compose build libv4l-build-cross-armhf
            docker-compose run --rm libv4l-build-cross-armhf

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          name: build_fixed
      - test:
          name: test_fixed
          requires:
            - build_fixed

      - build:
          name: build_stable
          rust: stable
      - test:
          name: test_stable
          rust: stable
          requires:
            - build_stable

      - cross_build:
          name: cross_build_fixed
      - cross_build:
          name: cross_build_stable
          rust: stable
