version: 2
jobs:
  build:
    working_directory: /tmp/libv4l_sys
    docker:
      - image: rust:1.36.0-buster
        environment:
          LIBCLANG_INCLUDE_PATH: /usr/include/clang/7/include
    steps:
      - checkout
      - run: git merge --no-edit origin/master
      - run:
          name: Setup Packages
          command: |
            apt-get update -y
            apt-get install -y libclang-7-dev libv4l-dev
      - run:
          name: Build crate
          command: |
            cargo build

  test:
    working_directory: /tmp/libv4l_sys
    docker:
      - image: rust:1.36.0-buster
        environment:
          LIBCLANG_INCLUDE_PATH: /usr/include/clang/7/include
    steps:
      - checkout
      - run: git merge --no-edit origin/master
      - run:
          name: Setup Packages
          command: |
            apt-get update -y
            apt-get install -y libclang-7-dev libv4l-dev
      - run:
          name: Cargo test
          command: |
            cargo test

  cross_build:
    working_directory: /tmp/libv4l_sys
    docker:
      - image: rust:1.36.0-buster
        environment:
          TARGET_ARCH: arm-unknown-linux-gnueabihf
          LIBCLANG_INCLUDE_PATH: /usr/include/clang/7/include
          PKG_CONFIG_PATH: /usr/lib/arm-linux-gnueabihf/pkgconfig
          PKG_CONFIG_ALLOW_CROSS: 1
    steps:
      - checkout
      - run: git merge --no-edit origin/master
      - run:
          name: Setup Packages
          command: |
            dpkg --add-architecture armhf
            apt-get update -y
            apt-get install -y libv4l-dev:armhf libclang-common-7-dev:armhf libclang-7-dev:armhf
            apt-get install -y gcc-arm-linux-gnueabihf libclang-7-dev
      - run:
          name: Install Rust for ARM
          command: |
            rustup target add ${TARGET_ARCH}
      - run:
          name: Build crate
          command: |
            cargo build --target=${TARGET_ARCH}
      - run:
          name: Build example
          command: |
            cargo build --target=${TARGET_ARCH} --example v4l2grab


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - cross_build

